# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

OAUTH_TOKEN_TYPE = 'Bearer'
AUTHORIZATION_CODE_GRANT = 'authorization_code'
CLIENT_CREDENTIAL_GRANT = 'client_credentials'
REFRESH_TOKEN = 'refresh_token'
SERVER_HOST = 'api.lyft.com'
ACCESS_TOKEN_PATH = 'oauth/token'
AUTHORIZE_PATH = 'oauth/authorize'
REVOKE_PATH = 'oauth/revoke_refresh_token'
CODE_RESPONSE_TYPE = 'code'
SANDBOX_MODE_PREFIX = 'SANDBOX'
VALID_RESPONSE_TYPES = frozenset([
    CODE_RESPONSE_TYPE,
])